### ISSUE TITLE
Question regarding solely as plugin to extends a theme

### ISSUE THREAD

**Issue by iniznet** [alleyinteractive/mantle#111]
Just found this great framework in searching for a plugin boilerplate/framework, it seems intended for building a full-fledged site so I wonder if I can use the framework for just plugin purposes for extending an existing theme? I'm already on the way to progressing my site with another framework that also uses some Laravel framework ability though not as whole as this one.

My primary plan is to use its database, orm, queues & scheduling task features.

**Comment by srtfisher** [comment]
You can use it in both regards! The https://github.com/alleyinteractive/mantle project is geared toward creating a plugin that will power the site and allow the theme to focus on styles/templates. The core of the site would remain in your plugin.

However, there is nothing stopping you from using Mantle as a theme, too. It just hasn't been built for that and might be a little bit of an uphill battle.

**Comment by iniznet** [comment]
Thanks! I've been using it for some of my projects but unlucky for a site with a Sage theme, it's seems tried to load the Acorn providers and I'm not sure how it able to detect providers belonging to Acorn when it's under their own package directory.

Do we have some workaround to exclude them?

Here's the log:
```
Mantle.ERROR: Skipping provider [Roots\Acorn\Providers\AcornServiceProvider] because it encountered an error [Error].
{"blogId":1,"userId":1,"exception":"[object] (Roots\\Acorn\\Exceptions\\SkipProviderException(code: 0): Skipping provider [Roots\\Acorn\\Providers\\AcornServiceProvider] because it encountered an error [Error].
at /www/wwwroot/(path-to-theme)/vendor/roots/acorn/src/Roots/Acorn/Application.php:390)\n[previous exception] [object] (Error(code: 0): Call to undefined method Mantle\\Framework\\Application::databasePath() at /www/wwwroot/(path-to-theme)/vendor/roots/acorn/src/Illuminate/Foundation/helpers.php:360)"} []
```

Front error:
Since it's still registering service providers and error occurred, Mantle whoops is still not able to intercept yet, so I'm still using Acorn Whoops. I plan to disable it and use the Mantle one later.
![image](https://user-images.githubusercontent.com/34362833/184220866-06339d29-8a85-4bc3-8ab7-9116c954591d.png)

**Comment by iniznet** [comment]
After trying on other non sage themes, it's been helpful so far. I'm planning to rebuild my site using mantle from sage.
