### ISSUE TITLE
Call to undefined method `WP_Post::name()`

### ISSUE THREAD

**Issue by renatonascalves** [alleyinteractive/mantle#163]
The doc has this example here: https://mantle.alley.com/docs/testing/requests#making-requests

```

$post = static::factory()->post->create_and_get();

$this->get( $post )
     ->assertSee( $post->name() );
```

But while testing, `$post->name()` is undefined. I can see the `Core_Object` interface, but the method that's implementing it.

**Comment by srtfisher** [comment]
Docs updated: https://mantle.alley.com/docs/testing/requests#making-requests
