### ISSUE TITLE
Clarify docs for Mantle's action and filter functions

### ISSUE THREAD

**Issue by johnbillion** [alleyinteractive/mantle#72]
Ref: https://mantle.alley.co/features/hooks/

It's not clear from this documentation what Mantle's `add_action()` and `add_filter()` functions are doing over and above core's. Could this documentation be improved?

**Comment by srtfisher** [comment]
I agree, it could be a bit clearer. The TL;DR is that it'll allow safe type-hinting when using `add_action()/`add_filter()` without a possible fatal. Will fix.

**Comment by srtfisher** [comment]
I hope this helps clarify it, sorry for the delay! https://mantle.alley.co/features/hooks.html#wrapper-on-core-actions-filters
